# To test it locally, use `act`: https://github.com/nektos/act

name: Tests
on: [push]
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update -y && \
          sudo apt-get install -y \
            clang \
            curl \
            exuberant-ctags \
            flex \
            gperf \
            libclang-dev \
            libssl-dev \
            libxml2-dev \
            llvm-dev \
            pkg-config \
            python3-dev \
            python3-pip \
            smitools \
            snmp-mibs-downloader \
            valgrind
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Install asdf
        uses: asdf-vm/actions/setup@v4
        with:
          asdf_branch: v0.15.0  # Keep this version for `asdf plugin-add`

      - name: Install waf
        run: |
          sudo curl https://waf.io/waf-2.0.24 -o /usr/local/bin/waf && \
          sudo chmod +x /usr/local/bin/waf && \
          sudo waf --help 2>&1 >/dev/null

      - name: Configure with GCC, default
        run: waf configure

      - name: Compile with GCC, default
        run: waf build

      - name: Check with GCC, default
        run: waf check

      - name: Clean-up
        run: waf clean

      - name: Configure with Clang, ASan
        run: waf configure
        env:
          CC: clang
          CXX: clang++
          P: asan

      - name: Compile with Clang, ASan
        run: waf build

      - name: Check with Clang, ASan
        run: waf check
        env:
          ASAN_OPTIONS: 'handle_segv=0:detect_leaks=1'

      - name: Static checks
        run: ./static-checks.sh
